aronmilenasol/personal-website

- src/app/[locale]/about/page.tsx
In this branch, I re-designed the About page to make it look more minimalistic, yet pink and professional.
- Removed the spans for the heart icons.
- Adopted a minimalistic and pink design, keeping professionalism.
> refactor: Redesign the about page.

- src/app/[locale]/projects/page.tsx
In this branch, I changed the background color and heading styles so they better match my new design.
- Changed the background color to pink.
- Modified the heading with the same styles as the about one.
> refactor: Background color and heading styles

- messages/en.json
- messages/es.json
- src/app/[locale]/about/page.tsx
- src/app/[locale]/components/AboutWebsite.tsx
In this branch, I incorporated the **About Website** section. This will allow visitors to see which are the technologies used to develop the website and to visit the repository so they can view the source code and documentation.
- Added the text content for the new section in the JSON files.
- Created the aboutWebsite component and integrated it into the page.
> feature: About Website section

- src/app/[locale]/page.tsx
In this branch, I fixed #37 by changing the alt description to a more appropriate one for the current image.
- Changed the alt description to one that better matches the image's content.
> bugfix: Change the alt description.

- src/app/[locale]/page.tsx
In this branch, I fixed #36 by adding the rel attributes noopener noreferrer in the homepage's button.
- Added the rel attributes noopener noreferrer to the homepage's button.
> bugfix: Add rel attributes to the button.

- src/app/[locale]/about/page.tsx
In this branch, I worked on #35 by removing the current studying paragraph from the about page.
- Remove the current studying paragraph from the about page.
> refactor: Remove studying paragraph.

- messages/en.json
- messages/es.json
- src/app/[locale]/components/ResumeExperience.tsx
Fixed #45 by incorporating my work experience in the component, which I forgot when I was dividing the page into smaller components.
- Added missing framework in the JSONs.
- Incorporated the work experience in the component.
> fix: Work Experience

- messages/en.json
- messages/es.json
- src/app/[locale]/components/Navbar.tsx
- src/app/[locale]/components/NowReading.tsx
- src/app/[locale]/currently/page.tsx
In this branch, I've added the Currently/Now page, which allows me to share what I'm doing regarding my career. I also added the first component: Now Reading, and the needed locales for this page to work in English and Spanish. 
- Added the English and Spanish locales for the page.
- Created the current page.
- Created the first component: Now Reading.
- Added the link for the new page to the navbar.
> feature: Currently Page

- src/app/[locale]/components/Navbar.tsx
In this branch, I removed the gallery link from the navbar, since I don't want to share it on my website.
- Removed the gallery link from the navbar.
> refactor: Remove the gallery link from the navbar

- src/app/[locale]/components/Navbar.tsx
In this branch, I've refactored the Navbar by creating an array for the links and iterating over it using the map method to render them dynamically. This follows the DRY principle, making the code more organized and maintainable. 
- Created an array to centralize navigation links.
- Rendered navigation links dynamically using the map method.
> refactor: Dynamic render Navbar Links.

- messages/en.json
- messages/es.json
In this branch, I've updated the book I'm currently reading by removing The Pragmatic Programmer and replacing it with Programming TypeScript. 
- Updated my current reading book.
> refactor: Update Currently Reading

- messages/en.json
- messages/es.json
- src/app/[locale]/about/page.tsx
- src/app/[locale]/components/about/AboutLikes.tsx
In this branch, I've created the Likes component, which lets people know what I love about being a software developer. 
- Added the locales for the component. 
- Created the component and integrated it into the page.
> feature: Likes Component

- messages/en.json
- messages/es.json
- src/app/[locale]/components/home/Hero.tsx
- src/app/[locale]/page.tsx
In this branch, I refactored the homepage by moving the hero into a separate component. I've also updated it by removing the description and integrating it with my name.
- Moved the hero into a separate component.
- Removed the description and integrated it with my name.
> refactor: Home

- messages/en.json
- messages/es.json
- src/app/[locale]/components/currently/NowReading.tsx
In this branch, I added a new book that I'm reading and I created a custom component for Book, in order to follow the DRY principles.
- Added a new book in Currently Reading.
- Added the locales for that book.
- Created a custom component for Book.
> refactor: Currently Reading

- src/app/[locale]/layout.tsx
In this branch, I added the` min-h-screen grid grid-rows-[auto_1fr_auto]` Tailwind classes to the body to make sure it looks good on all devices. 
- Added the `min-h-screen grid grid-rows-[auto_1fr_auto]` Tailwind classes to the body to make sure it looks good on all devices.
> fix: Add classes to the body to ensure it looks good on all devices

- messages/en.json
- messages/es.json
- src/app/[locale]/components/currently/WorkingOn.tsx
- src/app/[locale]/components/currently/WorkingProject.tsx
- src/app/[locale]/currently/page.tsx
In this branch, I've created the Working On section, which is featured on the Currently page. 
- Added the locales.
- Created the WorkingProject component.
- Created the WorkingOn component.
- Integrated the WorkingOn component as a section on the Currently page.
> feature: Working On

- messages/en.json
- messages/es.json
- src/app/[locale]/components/home/Hero.tsx
In this branch, I've modified the hero's appearance and updated the locales.
- Updated the locales.
- Modified the hero's appearance
> refactor: Homepage's Hero

- messages/en.json
- messages/es.json
- src/app/[locale]/about/page.tsx
- src/app/[locale]/components/about/AboutMe.tsx
- src/app/[locale]/components/about/AboutWebsite.tsx
- src/app/[locale]/components/about/CareerGoal.tsx
In this branch, I created two new components for the about page: Career Goal and About Me (the last one already existed, but it was in the` page.tsx` file). 
- Updated the About's locales.
- Created the About Me component.
- Added margin-bottom to the About Website component. 
- Created the Career Goal component.
- Added the new components to the About page.
> refactor: About Page

- package-lock.json
- package.json
- src/app/[locale]/layout.tsx
In this branch, I installed Clarity in replacement of Vercel Analytics.
- Installed Clarity.
- Removed Vercel Analytics.
> feature: Clarity

- src/app/[locale]/components/currently/NowReading.tsx
- src/app/[locale]/components/currently/WorkingOn.tsx
- src/app/[locale]/components/home/Hero.tsx
- src/app/[locale]/components/navbar/Navbar.tsx
- src/app/[locale]/components/navbar/ThemeSwitcher.tsx
- src/app/[locale]/components/project/ProjectCard.tsx
- src/app/[locale]/components/resume/ResumeEducation.tsx
- src/app/[locale]/components/resume/ResumeExperience.tsx
- src/app/[locale]/components/resume/ResumeLanguages.tsx
- src/app/[locale]/globals.css
In this branch, I changed the colors (inspired by Github's palette) and used a minimalism vibe, removing unnecessary icons or replacing them. I also changed the hero by removing the image and adapting it to the change.
- Changed the color and vibes to minimalism. 
- Removed unnecessary icons. 
- Removed the image from the hero.
> refactor: Design (color and vibes)

- messages/en.json
- messages/es.json
- src/app/[locale]/components/resume/ResumeEducation.tsx
- src/app/[locale]/currently/page.tsx
In this branch, I updated both languages so they match my current experience more closely. I also modified the space in the Currently page and updated my Education section.
- Updated both languages.
- Modified the space in the Currently page.
- Updated my Education section.
> chore: Update locales

- blog/en/old-notebook-homelab.md
- blog/es/old-notebook-homelab.md
- lib/blog.ts
- messages/en.json
- messages/es.json
- package-lock.json
- package.json
- src/app/[locale]/blog/[slug]/page.tsx
- src/app/[locale]/blog/page.tsx
- src/app/[locale]/components/navbar/Navbar.tsx
- src/app/[locale]/projects/page.tsx
- tailwind.config.ts
In this branch, I created a blog page using Remark. 
- Created blog page.
- Added the first post.
- Added typography in Tailwind. 
- Installed needed dependencies. 
- Updated projects page.
> feature: Blog

- blog/en/old-notebook-homelab.md
- blog/es/old-notebook-homelab.md
- package-lock.json
- src/app/[locale]/blog/[slug]/page.tsx
- src/app/[locale]/blog/page.tsx
In this branch, I incorporated the fix for params that wasn't allowing the app to deploy. I also fixed the date for the blog posts.
> fix: Params

- blog/en/old-notebook-homelab.md
- blog/es/old-notebook-homelab.md
- messages/en.json
- messages/es.json
- package-lock.json
- package.json
- src/app/[locale]/components/Footer.tsx
- src/app/[locale]/components/about/AboutWebsite.tsx
- src/app/[locale]/projects/page.tsx
On this branch, I updated my deprecated GitHub links, Next's version, and my locales.
> chore: Update Data

- blog/en/phoenix-project-review.md
- blog/es/phoenix-project-review.md
In this branch, I added Phoenix's Project book review.
> feature: Phoenix Project Review
